# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from nglm_grpc import nglm_pb2 as nglm__grpc_dot_nglm__pb2


class ServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/nglm_grpc.Server/register',
        request_serializer=nglm__grpc_dot_nglm__pb2.clientInfo.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.registerResponse.FromString,
        )
    self.isAlive = channel.unary_unary(
        '/nglm_grpc.Server/isAlive',
        request_serializer=nglm__grpc_dot_nglm__pb2.query.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )


class ServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def isAlive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=nglm__grpc_dot_nglm__pb2.clientInfo.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.registerResponse.SerializeToString,
      ),
      'isAlive': grpc.unary_unary_rpc_method_handler(
          servicer.isAlive,
          request_deserializer=nglm__grpc_dot_nglm__pb2.query.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nglm_grpc.Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LoggingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.start = channel.unary_unary(
        '/nglm_grpc.Logging/start',
        request_serializer=nglm__grpc_dot_nglm__pb2.params.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )
    self.output = channel.stream_unary(
        '/nglm_grpc.Logging/output',
        request_serializer=nglm__grpc_dot_nglm__pb2.chunks.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )
    self.err = channel.unary_unary(
        '/nglm_grpc.Logging/err',
        request_serializer=nglm__grpc_dot_nglm__pb2.exception.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )
    self.getConfig = channel.unary_stream(
        '/nglm_grpc.Logging/getConfig',
        request_serializer=nglm__grpc_dot_nglm__pb2.chunkSize.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.chunks.FromString,
        )
    self.setConfig = channel.stream_unary(
        '/nglm_grpc.Logging/setConfig',
        request_serializer=nglm__grpc_dot_nglm__pb2.chunks.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )


class LoggingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def start(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def output(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def err(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setConfig(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LoggingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'start': grpc.unary_unary_rpc_method_handler(
          servicer.start,
          request_deserializer=nglm__grpc_dot_nglm__pb2.params.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
      'output': grpc.stream_unary_rpc_method_handler(
          servicer.output,
          request_deserializer=nglm__grpc_dot_nglm__pb2.chunks.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
      'err': grpc.unary_unary_rpc_method_handler(
          servicer.err,
          request_deserializer=nglm__grpc_dot_nglm__pb2.exception.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
      'getConfig': grpc.unary_stream_rpc_method_handler(
          servicer.getConfig,
          request_deserializer=nglm__grpc_dot_nglm__pb2.chunkSize.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.chunks.SerializeToString,
      ),
      'setConfig': grpc.stream_unary_rpc_method_handler(
          servicer.setConfig,
          request_deserializer=nglm__grpc_dot_nglm__pb2.chunks.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nglm_grpc.Logging', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
