# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Server_Side.nglm_grpc import nglm_pb2 as nglm__grpc_dot_nglm__pb2


class ClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/nglm_grpc.Client/register',
        request_serializer=nglm__grpc_dot_nglm__pb2.clientInfo.SerializeToString,
        response_deserializer=nglm__grpc_dot_nglm__pb2.response.FromString,
        )


class ClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=nglm__grpc_dot_nglm__pb2.clientInfo.FromString,
          response_serializer=nglm__grpc_dot_nglm__pb2.response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nglm_grpc.Client', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
